src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 10)]
    private $phoneNumber;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Review::class)]
    private $reviews;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Participant::class)]
    private $participants;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Participant::class)]
    private $userParticipants;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->participants = new ArrayCollection();
        $this->userParticipants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setUser($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getUser() === $this) {
                $participant->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getUserParticipants(): Collection
    {
        return $this->userParticipants;
    }

    public function addUserParticipant(Participant $userParticipant): self
    {
        if (!$this->userParticipants->contains($userParticipant)) {
            $this->userParticipants[] = $userParticipant;
            $userParticipant->setUser($this);
        }

        return $this;
    }

    public function removeUserParticipant(Participant $userParticipant): self
    {
        if ($this->userParticipants->removeElement($userParticipant)) {
            // set the owning side to null (unless already changed)
            if ($userParticipant->getUser() === $this) {
                $userParticipant->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Security/securityController.php
<?php

declare(strict_types=1);

namespace App\Controller\Security;

use App\Entity\User;
use App\Form\RegisterFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class securityController extends AbstractController
{
    //Formulaire d'inscription :
    #[Route('/inscription', name: 'app_security_sign_up', methods: ['GET', 'POST'])]
    public function inscription(
        Request $request,
        EntityManagerInterface $em,
        UserPasswordHasherInterface $hasher,
    ): Response
    {

        $user = new User();

        $form = $this->createForm(RegisterFormType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $user->setRoles(['ROLE_USER']);
            $user->setPassword(
                $hasher->hashPassword(
                    $user, $form->get('password')->getData()
                )
            );
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('app_security_login');
        }

        return $this->render('security/sign-up.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //Formulaure de connexion
    #[Route('/connexion', name: 'app_security_login')]
    public function login(
        AuthenticationUtils $authenticationUtils
    ): Response
    {

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername, 'error' => $error
        ]);
    }

    // Déconnexion
    #[Route(path: '/deconnexion', name: 'app_security_log_out')]
    public function logout(): void
    {}
}

templates/security/login.html.twig
{% extends "base.html.twig" %}

{% block title %}Connexion{% endblock %}

{% block body %}

    <style>
        footer{
            display: none;
        }
        header{
            background: url('/assets/img/background/bg-header.jpg') no-repeat center center / cover;
        }
        header h1{
            font-family: 'Playfair Display', serif;
            text-transform: uppercase;
            text-align: center;
            color: #efece9;
            text-shadow:
                    1px 0 1px #d9ccbc,
                    0 1px 1px  #efece9,
                    2px 1px 1px #d9ccbc,
                    1px 2px 1px  #efece9,
                    3px 2px 1px #d9ccbc,
                    2px 3px 1px  #efece9,
                    4px 3px 1px #d9ccbc,
                    3px 4px 1px  #efece9,
                    5px 4px 1px #d9ccbc,
                    4px 5px 1px  #efece9,
                    6px 5px 1px #d9ccbc,
                    5px 6px 1px  #efece9,
                    7px 6px 1px #d9ccbc;
        }
        ul li{
            font-size: 1rem;
            text-align: left;
        }
        @media screen and (max-width: 320px){
            header h1{
                font-size: 2rem !important;
            }
        }
    </style>

    <header data-jarallax data-speed=".8">

        <div class="d-flex flex-column min-vh-100 bg-black-50 pt-10 pt-md-8 pb-7 pb-md-0">

            <div class="container my-auto">

                <div class="row justify-content-center">

                    <div class="col-12 col-md-10 col-lg-8 text-center">

                        <div class="display-3 text-white mb-4">

                            <form name="login" action="" method="post" class="m-3">

                                <div class="col-md-12">

                                    <h1 class="display-3" style="color: #f9f9f9;">Se <br> connecter</h1>

                                    {% if error %}
                                        <div class="alert alert-danger" style="font-size: 1rem">L'adresse et/ou le mot de passe sont incorrectes</div>
                                    {% endif %}

                                    {% if app.user %}
                                        <div>
                                            Vous êtes connecté en tant que {{ app.user.username }}, <a href="{{ path('app_user_logout') }}">Déconnexion</a>
                                        </div>
                                    {% endif %}

                                    <input placeholder="Email" type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control my-3" autocomplete="email" required autofocus>

                                    <input placeholder="Mot de passe" type="password" name="password" id="inputPassword" class="form-control my-3" autocomplete="current-password" required>

                                    <input type="hidden" name="_csrf_token"value="{{ csrf_token('authenticate') }}">

                                    <button class="btn btn-outline-primary text-white text-primary-hover mb-7 mb-md-0" type="submit">Se connecter</button>

                                </div>

                            </form>

                        </div>

                    </div>

                    <div class="nav justify-content-center text-center mt-5 d-flex" style="font-size: 1rem">
                        <p class="text-white">Vous n'avez pas de compte ? <br>
                            <a class="active" href="{{ path('app_security_sign_up') }}">
                                Inscrivez-vous
                            </a>
                        </p>
                    </div>

                </div>

            </div>

        </div>

    </header>

{% endblock %}

templates/security/sign-up.html.twig
{% extends "base.html.twig" %}

{% block title %}Inscription{% endblock %}

{% block body %}

    <style>
        footer{
            display: none;
        }
        header{
            background: url('/assets/img/background/bg-header.jpg') no-repeat center center / cover;
        }
        header h1{
            font-family: 'Playfair Display', serif;
            text-transform: uppercase;
            text-align: center;
            color: #efece9;
            text-shadow:
                    1px 0 1px #d9ccbc,
                    0 1px 1px  #efece9,
                    2px 1px 1px #d9ccbc,
                    1px 2px 1px  #efece9,
                    3px 2px 1px #d9ccbc,
                    2px 3px 1px  #efece9,
                    4px 3px 1px #d9ccbc,
                    3px 4px 1px  #efece9,
                    5px 4px 1px #d9ccbc,
                    4px 5px 1px  #efece9,
                    6px 5px 1px #d9ccbc,
                    5px 6px 1px  #efece9,
                    7px 6px 1px #d9ccbc;
        }
        ul li{
            font-size: 1rem;
            text-align: left;
        }
        @media screen and (max-width: 320px){
            header h1{
                font-size: 2.5rem !important;
            }
        }
    </style>

    <header data-jarallax data-speed=".8">

        <div class="d-flex flex-column min-vh-100 bg-black-50 pt-10 pt-md-8 pb-7 pb-md-0">

            <div class="container my-auto">

                <div class="row justify-content-center">

                    <div class="col-12 col-md-10 col-lg-8 text-center">

                        <div class="display-3 text-white mb-4">

                            <div class="col-md-12">

                                <h1 class="display-3" style="color: #f9f9f9;">S'inscrire</h1>

                                {{ form(form) }}

                            </div>

                        </div>

                    </div>

                    <div class="nav justify-content-center text-center mt-5 d-flex" style="font-size: 1rem">
                        <p class="text-white">Vous avez déjà un compte ? <br>
                            <a class="active" href="{{ path('app_security_login') }}">
                                Conectez-vous
                            </a>
                        </p>
                    </div>

                </div>

            </div>

        </div>

    </header>

{% endblock %}